ignore:
  - "src/main/java/edu/fiuba/algo3/controlador"
  - "src/main/java/edu/fiuba/algo3/vista"
  - "src/main/java/edu/fiuba/algo3/App.java"
  - "src/main/java/edu/fiuba/algo3/Main.java"
  - "src/main/java/edu/fiuba/algo3/SystemInfo.java"
  - "src/main/java/edu/fiuba/algo3/MessagesFileInvalid.java"
  - "src/main/java/edu/fiuba/algo3/Message.java"
  - "src/main/java/edu/fiuba/algo3/Localize.java"
  - "src/main/java/edu/fiuba/algo3/MessageRepository.java"