ignore:
  - "src/main/java/edu/fiuba/algo3/controlador"
  - "src/main/java/edu/fiuba/algo3/vista"
  - "src/main/java/edu/fiuba/algo3/App.java"
  - "src/main/java/edu/fiuba/algo3/Main.java"
  - "src/main/java/edu/fiuba/algo3/SystemInfo.java"
  - "src/main/java/edu/fiuba/algo3/modelo/MessagesFileInvalid.java"
  - "src/main/java/edu/fiuba/algo3/modelo/Message.java"
  - "src/main/java/edu/fiuba/algo3/modelo/Localize.java"
  - "src/main/java/edu/fiuba/algo3/modelo/MessageRepository.java"
  - "src/main/java/edu/fiuba/algo3/repositorios/JsonMessageRepository.java"