name: build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start services
        run: scripts/start_services.sh
      - name: Run test suite
        run: docker compose -f docker/docker-compose.yaml exec -T app bash scripts/build.sh
      - name: Run mutation test
        run: docker compose -f docker/docker-compose.yaml exec -T app bash scripts/run_mutation_test.sh
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: paramiomarcelo/algo3_tp2

  package:
    runs-on: ubuntu-22.04
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start services
        run: scripts/start_services.sh
      - name: Package
        run: docker compose -f docker/docker-compose.yaml exec -T app bash scripts/package.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/tp2-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
